=== SergeyPodgayskiy/MovieRatingFinalProject/src/main/resources/commands.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://epam.com/movierating_commands"
            xmlns:tns="http://epam.com/movierating_commands"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">
    <xsd:element name="commands" type="tns:Commands"/>

    <xsd:complexType name="Commands">
        <xsd:sequence>
            <xsd:element name="command" type="tns:Command" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Command">
        <xsd:sequence>
            <xsd:element name="command-name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="command-class" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== SergeyPodgayskiy/MovieRatingFinalProject/src/main/resources/commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<commands xmlns="http://epam.com/movierating_commands"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://epam.com/movierating_commands commands.xsd ">

    <!--general commands-->
    <command>
        <command-name>show-welcome-page</command-name>
        <command-class>by.epam.movierating.command.impl.general.ShowWelcomePageCommand</command-class>
    </command>
    <command>
        <command-name>show-admin-page</command-name>
        <command-class>by.epam.movierating.command.impl.general.ShowAdminPageCommand</command-class>
    </command>
    <command>
        <command-name>redirect</command-name>
        <command-class>by.epam.movierating.command.impl.general.RedirectCommand</command-class>
    </command>

    <!--user commands-->
    <command>
        <command-name>log-in</command-name>
        <command-class>by.epam.movierating.command.impl.user.LogInCommand</command-class>
    </command>
    <command>
        <command-name>log-out</command-name>
        <command-class>by.epam.movierating.command.impl.user.LogOutCommand</command-class>
    </command>
    <command>
        <command-name>register</command-name>
        <command-class>by.epam.movierating.command.impl.user.RegisterCommand</command-class>
    </command>
    <command>
        <command-name>rate-movie</command-name>
        <command-class>by.epam.movierating.command.impl.user.RateMovieCommand</command-class>
    </command>
    <command>
        <command-name>update-movie-rating</command-name>
        <command-class>by.epam.movierating.command.impl.user.UpdateMovieRatingCommand</command-class>
    </command>
    <command>
        <command-name>delete-movie-rating</command-name>
        <command-class>by.epam.movierating.command.impl.user.DeleteMovieRatingCommand</command-class>
    </command>
    <command>
        <command-name>change-language</command-name>
        <command-class>by.epam.movierating.command.impl.user.ChangeLanguageCommand</command-class>
    </command>
    <command>
        <command-name>check-rate-opportunity</command-name>
        <command-class>by.epam.movierating.command.impl.user.CheckRateOpportunityCommand</command-class>
    </command>


    <!--admin commands-->
    <command>
        <command-name>update-admin-status</command-name>
        <command-class>by.epam.movierating.command.impl.admin.UpdateAdminStatusCommand</command-class>
    </command>
    <command>
        <command-name>update-ban-status</command-name>
        <command-class>by.epam.movierating.command.impl.admin.UpdateBanStatusCommand</command-class>
    </command>
    <command>
        <command-name>delete-user</command-name>
        <command-class>by.epam.movierating.command.impl.admin.DeleteUserCommand</command-class>
    </command>
    <command>
        <command-name>show-users</command-name>
        <command-class>by.epam.movierating.command.impl.admin.ShowUsersCommand</command-class>
    </command>

    <!--movie commands-->
    <command>
        <command-name>show-top-movies</command-name>
        <command-class>by.epam.movierating.command.impl.movie.ShowTopMoviesCommand</command-class>
    </command>
    <command>
        <command-name>show-most-discussed-movies</command-name>
        <command-class>by.epam.movierating.command.impl.movie.ShowMostDiscussedMoviesCommand</command-class>
    </command>
    <command>
        <command-name>show-movie-page</command-name>
        <command-class>by.epam.movierating.command.impl.movie.ShowMoviePageCommand</command-class>
    </command>
    <command>
        <command-name>create-movie</command-name>
        <command-class>by.epam.movierating.command.impl.movie.CreateMovieCommand</command-class>
    </command>
    <command>
        <command-name>update-movie</command-name>
        <command-class>by.epam.movierating.command.impl.movie.UpdateMovieCommand</command-class>
    </command>
    <command>
        <command-name>add-country-for-movie</command-name>
        <command-class>by.epam.movierating.command.impl.movie.AddCountryForMovieCommand</command-class>
    </command>
    <command>
        <command-name>delete-country-for-movie</command-name>
        <command-class>by.epam.movierating.command.impl.movie.DeleteCountryForMovieCommand</command-class>
    </command>
    <command>
        <command-name>add-language-dependent-movie-info</command-name>
        <command-class>by.epam.movierating.command.impl.movie.AddLanguageDependentMovieInfoCommand</command-class>
    </command>
    <command>
        <command-name>add-participant-for-movie</command-name>
        <command-class>by.epam.movierating.command.impl.movie.AddParticipantForMovieCommand</command-class>
    </command>
    <command>
        <command-name>delete-participant-for-movie</command-name>
        <command-class>by.epam.movierating.command.impl.movie.DeleteParticipantForMovieCommand</command-class>
    </command>
    <command>
        <command-name>add-genre-for-movie</command-name>
        <command-class>by.epam.movierating.command.impl.movie.AddGenreForMovieCommand</command-class>
    </command>
    <command>
        <command-name>delete-genre-for-movie</command-name>
        <command-class>by.epam.movierating.command.impl.movie.DeleteGenreForMovieCommand</command-class>
    </command>
    <command>
        <command-name>check-language-movie-info-by-code</command-name>
        <command-class>by.epam.movierating.command.impl.movie.CheckLanguageMovieInfoByCodeCommand</command-class>
    </command>
    <command>
        <command-name>get-language-movie-info-by-code</command-name>
        <command-class>by.epam.movierating.command.impl.movie.GetLanguageMovieInfoByCodeCommand</command-class>
    </command>
    <command>
        <command-name> update-language-dependent-movie-info</command-name>
        <command-class>by.epam.movierating.command.impl.movie.UpdateLangDependentMovieInfoCommand</command-class>
    </command>
    <command>
        <command-name>delete-movie</command-name>
        <command-class>by.epam.movierating.command.impl.movie.DeleteMovieCommand</command-class>
    </command>
    <command>
        <command-name>show-edit-movie-page</command-name>
        <command-class>by.epam.movierating.command.impl.movie.ShowEditMoviePageCommand</command-class>
    </command>
    <command>
        <command-name>get-neutral-movie-information</command-name>
        <command-class>by.epam.movierating.command.impl.movie.GetNeutralMovieInfoCommand</command-class>
    </command>


    <!--participant commands-->
    <command>
        <command-name>get-all-movieroles</command-name>
        <command-class>by.epam.movierating.command.movierole.GetAllMovieRolesCommand</command-class>
    </command>
    <command>
        <command-name>get-all-participants-by-role-id</command-name>
        <command-class>by.epam.movierating.command.impl.participant.GetAllParticipantsByRoleIdCommand</command-class>
    </command>
    <command>
        <command-name>get-participants-in-movie</command-name>
        <command-class>by.epam.movierating.command.impl.participant.GetParticipantsInMovieCommand</command-class>
    </command>

    <!--countries commands-->
    <command>
        <command-name>get-all-countries</command-name>
        <command-class>by.epam.movierating.command.impl.country.GetAllCountriesCommand</command-class>
    </command>
    <command>
        <command-name>get-countries-in-movie</command-name>
        <command-class>by.epam.movierating.command.impl.country.GetCountriesInMovieCommand</command-class>
    </command>

    <!--genres commands-->
    <command>
        <command-name>get-all-genres</command-name>
        <command-class>by.epam.movierating.command.impl.genre.GetAllGenresCommand</command-class>
    </command>
    <command>
        <command-name>get-genres-in-movie</command-name>
        <command-class>by.epam.movierating.command.impl.genre.GetGenresInMovieCommand</command-class>
    </command>
</commands>
